### ISSUE TITLE
Module not found: Can't resolve 'fbjs/lib/shallowEqual'

### ISSUE THREAD

**Issue by ahmedch1** [gitname/solar-ui#4]
I have cloned the project , created npm install then npm start,
I have got this message
./node_modules/semantic-ui-react/dist/es/lib/shallowEqual.js
Module not found: Can't resolve 'fbjs/lib/shallowEqual' 

Thanks in advance

**Comment by gitname** [comment]
Hi @ahmedch1, thanks for creating this issue. Although I failed to reproduce the specific error you reported, I did see that (a) `$ npm install` wasn't working (in my case, it was due to a conflict between the React version required by this app and the React version required by the version of Semantic UI this app uses), and (b) this repository didn't contain a `package-lock.json` file. 

I have since fixed both of those things (in commit https://github.com/gitname/solar-ui/commit/a553bb792af04c21908d8266d79a09b6d4de6fad). In case you still want to get this app running on your system, I recommend you use [version `0.2.0`](https://github.com/gitname/solar-ui/commit/16bbaa156696fbfe582f3614575c42f74cc74f4f) of this repo.
